#!/usr/bin/env python
"""
Non-rigorous Torch prefilter for finite upper-triangular Toeplitz/PF minors.

This script is a speed/suspicion tool only. It uses floating-point Torch
determinants on the same structurally nonzero minors as arb_toeplitz_pf_probe.py.
It must never be cited as a certificate: any negative, nonfinite, or near-zero
minor reported here needs Arb/interval follow-up.

The optional geometric scaling replaces c_k by c_k * p^k with p > 0. For a
minor with row set R and column set C, this multiplies the determinant by
p^(sum(C)-sum(R)), so signs are preserved while the coefficient dynamic range
can become much friendlier to float64 arithmetic.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict, dataclass
from decimal import Decimal, getcontext
from functools import lru_cache
import itertools
import json
import math
from pathlib import Path
from typing import Iterable


@dataclass
class ProblemRow:
    kind: str
    lam: str
    sequence: str
    matrix_size: int
    order: int
    rows: str
    cols: str
    det: float | None
    classification: str


def load_coefficients(path: Path, lam: str) -> list[str]:
    target = Decimal(lam)
    best: list[str] | None = None
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            row = json.loads(line)
            if row.get("kind") != "coefficients":
                continue
            try:
                cached_lam = Decimal(str(row["lam"]))
            except Exception:
                continue
            if cached_lam == target:
                values = list(row["A"])
                if best is None or len(values) > len(best):
                    best = values
    if best is None:
        raise RuntimeError(f"No coefficient row found for lambda={lam} in {path}")
    return best


def base_sequence(values: list[str], sequence: str, size: int) -> list[Decimal]:
    if size > len(values):
        raise RuntimeError(f"Need {size} coefficients, cache has {len(values)}")
    out: list[Decimal] = []
    for k, value in enumerate(values[:size]):
        ak = Decimal(value)
        if sequence == "beta":
            out.append(ak)
        elif sequence == "taylor":
            out.append(ak / Decimal(math.factorial(k)))
        else:
            raise ValueError(f"Unknown sequence {sequence!r}")
    return out


def geometric_scale_value(seq: list[Decimal], setting: str) -> float:
    if setting == "none":
        return 1.0
    if setting != "auto":
        value = float(setting)
        if not math.isfinite(value) or value <= 0:
            raise ValueError("--geometric-scale must be 'none', 'auto', or a positive finite number")
        return value

    nonzero = [(k, abs(x)) for k, x in enumerate(seq) if x != 0]
    if len(nonzero) < 2:
        return 1.0
    first_k, first_v = nonzero[0]
    last_k, last_v = nonzero[-1]
    if last_k == first_k:
        return 1.0
    log_p = (math.log(float(first_v)) - math.log(float(last_v))) / (last_k - first_k)
    return math.exp(log_p)


def scaled_float_sequence(seq: list[Decimal], geometric_scale: float) -> list[float]:
    out: list[float] = []
    log_p = math.log(geometric_scale)
    for k, value in enumerate(seq):
        if value == 0:
            out.append(0.0)
            continue
        sign = -1.0 if value < 0 else 1.0
        scaled_log = math.log(float(abs(value))) + k * log_p
        out.append(sign * math.exp(scaled_log))
    return out


def constrained_nonstructural_cols(rows: tuple[int, ...], size: int) -> Iterable[tuple[int, ...]]:
    order = len(rows)
    current: list[int] = []

    def rec(pos: int, previous: int):
        if pos == order:
            yield tuple(current)
            return
        lower = max(previous + 1, rows[pos])
        upper = size - (order - pos)
        for col in range(lower, upper + 1):
            current.append(col)
            yield from rec(pos + 1, col)
            current.pop()

    yield from rec(0, -1)


def count_constrained_nonstructural_cols(rows: tuple[int, ...], size: int) -> int:
    """Count columns generated by constrained_nonstructural_cols without enumerating them."""
    order = len(rows)

    @lru_cache(maxsize=None)
    def rec(pos: int, previous: int) -> int:
        if pos == order:
            return 1
        lower = max(previous + 1, rows[pos])
        upper = size - (order - pos)
        return sum(rec(pos + 1, col) for col in range(lower, upper + 1))

    return rec(0, -1)


def classify_det(det: float, near_zero_abs: float) -> str:
    if not math.isfinite(det):
        return "nonfinite"
    if abs(det) <= near_zero_abs:
        return "near_zero"
    if det < 0:
        return "negative"
    return "positive"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--coeff-cache", type=Path, required=True)
    parser.add_argument("--lambda", dest="lam", default="0")
    parser.add_argument("--sequence", choices=["beta", "taylor"], default="taylor")
    parser.add_argument("--matrix-size", type=int, default=10)
    parser.add_argument("--max-order", type=int, default=4)
    parser.add_argument("--device", choices=["auto", "cpu", "cuda"], default="auto")
    parser.add_argument("--dtype", choices=["float64", "float32"], default="float64")
    parser.add_argument("--batch-size", type=int, default=65536)
    parser.add_argument("--near-zero-abs", type=float, default=0.0)
    parser.add_argument("--geometric-scale", default="auto")
    parser.add_argument("--record-limit", type=int, default=100)
    parser.add_argument(
        "--skip-evaluations",
        type=int,
        default=0,
        help="Skip this many structurally nonzero minors before evaluating; useful for non-rigorous windowed scouting.",
    )
    parser.add_argument("--max-evaluations", type=int, default=None)
    parser.add_argument("--out-jsonl", type=Path, default=None)
    parser.add_argument("--out-summary", type=Path, default=None)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.max_order < 1 or args.max_order > args.matrix_size:
        raise ValueError("--max-order must be between 1 and --matrix-size")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be positive")
    if args.near_zero_abs < 0:
        raise ValueError("--near-zero-abs must be nonnegative")
    if args.skip_evaluations < 0:
        raise ValueError("--skip-evaluations must be nonnegative")
    if args.max_evaluations is not None and args.max_evaluations < 1:
        raise ValueError("--max-evaluations must be positive when provided")

    import torch

    if args.device == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA requested but torch.cuda.is_available() is false")
        device = torch.device("cuda")
    elif args.device == "auto" and torch.cuda.is_available():
        device = torch.device("cuda")
    else:
        device = torch.device("cpu")

    dtype = torch.float64 if args.dtype == "float64" else torch.float32
    if device.type == "cuda" and dtype == torch.float64:
        capability = torch.cuda.get_device_capability(device)
        if capability[0] < 6:
            raise RuntimeError(f"CUDA device capability {capability} is too old for float64 screening")

    getcontext().prec = 120
    values = load_coefficients(args.coeff_cache, args.lam)
    seq_decimal = base_sequence(values, args.sequence, args.matrix_size)
    scale = geometric_scale_value(seq_decimal, args.geometric_scale)
    seq_float = scaled_float_sequence(seq_decimal, scale)
    seq_t = torch.tensor(seq_float, dtype=dtype, device=device)

    counts: Counter[str] = Counter()
    records: list[ProblemRow] = []
    tests = 0
    skipped = 0
    evaluated = 0
    min_det: float | None = None
    min_abs_det: float | None = None
    truncated = False

    for order in range(1, args.max_order + 1):
        total_order_tests = math.comb(args.matrix_size, order) ** 2
        nonstructural_order = 0
        rows_t_cache: dict[tuple[int, ...], object] = {}

        for rows in itertools.combinations(range(args.matrix_size), order):
            row_tensor = rows_t_cache.get(rows)
            if row_tensor is None:
                row_tensor = torch.tensor(rows, dtype=torch.long, device=device)
                rows_t_cache[rows] = row_tensor

            if skipped < args.skip_evaluations:
                row_nonstructural = count_constrained_nonstructural_cols(rows, args.matrix_size)
                remaining_skip = args.skip_evaluations - skipped
                if row_nonstructural <= remaining_skip:
                    skipped += row_nonstructural
                    nonstructural_order += row_nonstructural
                    continue

            batch: list[tuple[int, ...]] = []
            for cols in constrained_nonstructural_cols(rows, args.matrix_size):
                if skipped < args.skip_evaluations:
                    skipped += 1
                    nonstructural_order += 1
                    continue
                batch.append(cols)
                reached_eval_cap = args.max_evaluations is not None and evaluated + len(batch) >= args.max_evaluations
                if len(batch) >= args.batch_size or reached_eval_cap:
                    evaluated_now, records_now, min_det, min_abs_det = evaluate_batch(
                        seq_t,
                        row_tensor,
                        rows,
                        batch,
                        args,
                        counts,
                        records,
                        min_det,
                        min_abs_det,
                    )
                    evaluated += evaluated_now
                    nonstructural_order += evaluated_now
                    batch = []
                    if reached_eval_cap:
                        truncated = True
                        break
            if batch and not truncated:
                evaluated_now, records_now, min_det, min_abs_det = evaluate_batch(
                    seq_t,
                    row_tensor,
                    rows,
                    batch,
                    args,
                    counts,
                    records,
                    min_det,
                    min_abs_det,
                )
                evaluated += evaluated_now
                nonstructural_order += evaluated_now
                if args.max_evaluations is not None and evaluated >= args.max_evaluations:
                    truncated = True
            if truncated:
                break

        if truncated:
            tests += nonstructural_order
            break
        counts["structural_zero"] += total_order_tests - nonstructural_order
        tests += total_order_tests

    summary = {
        "kind": "torch_toeplitz_prefilter_summary",
        "rigorous": False,
        "lam": args.lam,
        "sequence": args.sequence,
        "matrix_size": args.matrix_size,
        "max_order": args.max_order,
        "device": str(device),
        "dtype": args.dtype,
        "torch_version": torch.__version__,
        "cuda_available": bool(torch.cuda.is_available()),
        "geometric_scale": scale,
        "near_zero_abs": args.near_zero_abs,
        "batch_size": args.batch_size,
        "skip_evaluations": args.skip_evaluations,
        "tests_accounted": tests,
        "skipped_nonstructural_tests": skipped,
        "evaluated_nonstructural_tests": evaluated,
        "counts": dict(counts),
        "min_det": min_det,
        "min_abs_det": min_abs_det,
        "recorded_problem_rows": len(records),
        "truncated": truncated,
        "ok_for_screen": counts.get("negative", 0) == 0
        and counts.get("near_zero", 0) == 0
        and counts.get("nonfinite", 0) == 0,
        "proof_boundary": "non-rigorous floating-point screen; follow up with Arb before making certificate claims",
    }

    if args.out_jsonl is not None:
        args.out_jsonl.parent.mkdir(parents=True, exist_ok=True)
        with args.out_jsonl.open("w", encoding="utf-8") as f:
            for row in records:
                f.write(json.dumps(asdict(row), sort_keys=True) + "\n")
    if args.out_summary is not None:
        args.out_summary.parent.mkdir(parents=True, exist_ok=True)
        with args.out_summary.open("w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2, sort_keys=True)
            f.write("\n")

    print(json.dumps(summary, sort_keys=True))
    return 0 if summary["ok_for_screen"] else 1


def evaluate_batch(
    seq_t,
    row_tensor,
    rows: tuple[int, ...],
    batch: list[tuple[int, ...]],
    args: argparse.Namespace,
    counts: Counter[str],
    records: list[ProblemRow],
    min_det: float | None,
    min_abs_det: float | None,
):
    import torch

    cols_t = torch.tensor(batch, dtype=torch.long, device=seq_t.device)
    diff = cols_t[:, None, :] - row_tensor[None, :, None]
    valid = diff >= 0
    mats = torch.where(valid, seq_t[torch.clamp(diff, min=0)], torch.zeros((), dtype=seq_t.dtype, device=seq_t.device))
    dets = torch.linalg.det(mats).detach().cpu().tolist()

    for cols, det in zip(batch, dets):
        det_f = float(det)
        classification = classify_det(det_f, args.near_zero_abs)
        counts[classification] += 1
        if math.isfinite(det_f):
            min_det = det_f if min_det is None else min(min_det, det_f)
            abs_det = abs(det_f)
            min_abs_det = abs_det if min_abs_det is None else min(min_abs_det, abs_det)
        if classification in {"negative", "near_zero", "nonfinite"} and len(records) < args.record_limit:
            records.append(
                ProblemRow(
                    kind="torch_toeplitz_prefilter_problem",
                    lam=args.lam,
                    sequence=args.sequence,
                    matrix_size=args.matrix_size,
                    order=len(rows),
                    rows=str(rows),
                    cols=str(cols),
                    det=det_f if math.isfinite(det_f) else None,
                    classification=classification,
                )
            )
    return len(batch), records, min_det, min_abs_det


if __name__ == "__main__":
    raise SystemExit(main())
